### ISSUE TITLE
CSD17484F4 causes an error

### ISSUE THREAD

**Issue by HenniePeters** [HenniePeters/LTSpice#2]
Error on line 32 : .model u1:pmosd pmos ( level = 7 capmod = 0  tnom = 27 vto = -1.0 nch = 5e15  tox = 1.75e-8 k1 = 0.65 k2 =-0.01  js = 0  cj = 1e-18 cjsw = 1e-18 noff = 2.0  cgso = 1e-18 cgdo = 1e-18 cgbo = 1e-18 )
	* Unrecognized parameter "vto" -- ignored
Direct Newton iteration for .op point succeeded.

In nmos/Texas/CSD17484F4.lib, I changed this line:
+ TNOM   = 27            VTO    = -1.0	  	NCH	 = 5e15

to:
+ TNOM   = 27            NCH	 = 5e15

I don't know what the consequences are but the simulation runs without errors now.

**Comment by HenniePeters** [comment]
For bsim3 'vto' seems to be spelled 'vth0'
vth0=-1.0 is accepted by LTSpice, is it really the same?

**Comment by speja** [comment]
There seems to be good correlation with the graphs in the data sheet...
